version: "3.3"
services:

  consul:
    image: consul:1.4.0
    ports:
      - "127.0.0.1:8500:8500"
    command: "agent -dev -bootstrap -ui -client 0.0.0.0"

  jaeger:
    image: jaegertracing/all-in-one:1.13.1
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  pushwateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  redis:
    image: redis:5-alpine
    ports:
      - '127.0.0.1:6379:6379'
