// Code generated by gitlab.fbs-d.com/dev/amqp-rpc-generator/protoc-gen-consulroute. DO NOT EDIT.
// source: proto/common.proto

package counter

import (
	"encoding/json"
	"fmt"
	"strings"
)

var (
	_ = fmt.Errorf
	_ = json.Unmarshal
	_ = strings.Replace
)

// Consul routings
